variables:
  OPENSSL_DIR: "/usr"
  OPENSSL_LIB_DIR: "/usr/lib"
  OPENSSL_INCLUDE_DIR: "/usr/include"
  POSTGRES_DB: erotic-hub
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_HOST_AUTH_METHOD: trust
  DATABASE_URL: "postgres://user:password@postgres:5432/erotic-hub"
  PKG_CONFIG_PATH: "/usr/lib/pkgconfig:/usr/local/lib/pkgconfig"


default:
  image: rust:latest
  services:
    - postgres:13
  before_script:
    - apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
      gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
      gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
      gstreamer1.0-libav libgstrtspserver-1.0-dev libges-1.0-dev \
      gstreamer1.0-tools
    - apt-get install build-base musl-dev gcc g++ openssl-dev
    - rustc --version
    - cargo --version
    - cargo install sqlx-cli
    - sqlx migrate run
  tags:
    - shared-fi

stages:
  - build
  - test

build:
  stage: build
  script:
    - find /usr/lib -name "libgstreamer-1.0.so" -o -name "libgobject-2.0.so" -o -name "libglib-2.0.so" -o -name "libintl.so"
    - pkg-config --cflags --libs gstreamer-1.0
    - cargo build --verbose
  cache:
    - key: "$CI_COMMIT_REF_SLUG"
      paths:
        - target/

      policy: push

lint:
  stage: test
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check
    - rustup component add clippy
    - cargo clippy -- -D warnings

  cache:
    - key: "$CI_COMMIT_REF_SLUG"
      paths:
        - target/

      policy: pull

test:
  stage: test
  script:
    - cargo test --verbose
  cache:
    - key: "$CI_COMMIT_REF_SLUG"
      paths:
        - target/

      policy: pull
