variables:
  POSTGRES_DB: erotic-hub
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_HOST_AUTH_METHOD: trust
  DATABASE_URL: "postgres://user:password@postgres:5432/erotic-hub"


default:
  image: ricaps/gstreamer-rust:latest
  services:
    - postgres:13
  before_script:
    - rustc --version
    - cargo --version
    - sqlx migrate run
  tags:
    - shared-fi

stages:
  - build
  - test

build:
  stage: build
  script:
    - cargo build --verbose
  cache:
    - key: "$CI_COMMIT_REF_SLUG"
      paths:
        - target/

      policy: push

lint:
  stage: test
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check
    - rustup component add clippy
    - cargo clippy -- -D warnings

  cache:
    - key: "$CI_COMMIT_REF_SLUG"
      paths:
        - target/

      policy: pull

test:
  stage: test
  script:
    - cargo test --verbose
  cache:
    - key: "$CI_COMMIT_REF_SLUG"
      paths:
        - target/

      policy: pull
