app:
  file_size_limit_mb: 1000
  video:
    accepted_mime_type:
      - "video/mp4"
  thumbnail:
    accepted_mime_type:
      - "image/png"
  stream:
    resolutions:
      - "360"
      - "480"
      - "720"