version: "3.1"

services:
    erotic-hub:
      container_name: erotic-hub
      tty: true
      build:
        context: .
        dockerfile: docker/erotic-hub/Dockerfile
      environment:
        - DATABASE_URL=${DATABASE_URL}
        - REDIS_DATABASE_URL=${REDIS_DATABASE_URL}
        - RTMP_SERVER=${RTMP_SERVER}
        - NGINX_HLS_URL=${NGINX_HLS_URL}
        - STREAM_PATH_PREFIX=${STREAM_PATH_PREFIX}
        - SESSION_SECRET_KEY=${SESSION_SECRET_KEY}
        - EH_HOST=${EH_HOST}
        - EH_PORT=${EH_PORT}
        - RUST_LOG=${RUST_LOG}
        - SEED_DATA=${SEED_DATA}
        - ADMIN_USERNAME=${ADMIN_USERNAME}
        - ADMIN_PASSWORD=${ADMIN_PASSWORD}
        - ADMIN_EMAIL=${ADMIN_EMAIL}
      ports:
        - "8000:8000"
      depends_on:
        - "db"
        - "redis"
        - "nginx"
      volumes:
        - ./docker/erotic-hub/data:/usr/init-data
      profiles:
        - release
    # List of services to run
    db:
        # PostgreSQL database service
        image: postgres # Specify image to build container from, in this case latest postgres (https://hub.docker.com/_/postgres)
        restart: always # If container stops, always restart it
        environment:
            POSTGRES_PASSWORD: example # Set password for postgres (default) user
        ports:
            - "5432:5432" # Maps the port host:container
        healthcheck:
          test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
          interval: 30s
          timeout: 90s
          retries: 5
        volumes:
          - ./docker/postgres/db-data:/docker-entrypoint-initdb.d

    adminer:
        # Adminer web UI service
        image: adminer # Use latest adminer image (https://hub.docker.com/_/adminer/)
        restart: always
        profiles:
          - dev
        ports:
            - "8080:8080" # Maps the port host:container

    redis:
        # Redis database service
        image: redis # Use the official Redis image (https://hub.docker.com/_/redis)
        restart: always # If container stops, always restart it
        ports:
            - "6379:6379" # Maps the port host:container
        healthcheck:
          test: ["CMD", "redis-cli","ping"]
          interval: 30s
          timeout: 90s
          retries: 5
        profiles:
          - release
          - dev
    nginx:
      container_name: nginx-rtmp
      build: docker/nginx-rtmp/.
      restart: always
      tty: true
      environment:
        - NGINX_HLS_PUBLIC_URL=${NGINX_HLS_URL}
        - EH_AUTH_ENDPOINT=http://host.docker.internal:8000/stream/auth # URL for authentication Sub-request
      ports:
        - "1935:1935"
        - "8081:80"
      profiles:
         - release
         - dev
